### ISSUE TITLE
Upload images trop grosse ne fonctionne pas

### ISSUE THREAD

**Issue by luc38090** [YunoHost-Apps/hubzilla-yunohost#3]
Je suis en train de tester Hubzilla.
Tout fonctionne bien pour le moment, merci à l'auteur du package !
Petit problème: l'upload d'images d'environ 3Mo: ça plante.
J'essaye d'uploader et ça me dit:

```
413 Request Entity Too Large
```

Après quelques recherches, j'ai trouvé une config à modifier:
/etc/nginx/conf.d/nom.de.domaine.conf

j'y ajoute

```
client_max_body_size 20m;
client_body_buffer_size 128k;
```

Du coup je n'ai plus de message d'erreur, mais je me retrouve avec un fichier à 0ko dans hubzilla...
Rien dans les logs /var/log/nginx/nom.de.domaine-error.log (alors qu'avant la modif de config il y avait bien erreur)

J'ai activé les logs hubzilla dans la partie admin... et ça me donne ça quand je veux uploader un fichier trop gros:

```
2016-01-11 20:08:13:na3fsq8jqu5cus7v8ojpsp7a42 attach.php:433:attach_store: arr: Array
(
[q] => /photos/luc
[source] => photos
[newalbum] => 2016-01
[group_allow] => Array
(
[0] => c3999ca1ad3c745da1b6ac88d829cb57e8601bd3c93bb39a42b60accd14b1434Friends
)

[description] =>
[body] => 
[submit] =>

)
```

Pas très parlant...
Des idées ?

**Comment by anaqreon** [comment]
This sounds like a question better suited to the [Hubzilla support forums](https://gurus.red/channel/one). I just updated the sources to the latest stable version 1.1. Perhaps that will help.
