### ISSUE TITLE
Hubzilla 2.0 Released

### ISSUE THREAD

**Issue by anaqreon** [YunoHost-Apps/hubzilla-yunohost#8]
You may wish to upgrade the sources for Hubzilla 2.0 that was released a few days ago. It offers significant enhancements.

https://hubzilla.org/channel/hubzilla

**Comment by isAAAc** [comment]
i found this in the faq of hubzilla, is it safe on a Ynh install ?
How do I update a non-Git install?


1) Backup .htconfig.php
2) Backup everything in store/
3) Backup any custom changes in mod/site/ and view/site
3) Delete your existing installation
4) Upload the new version.
5) Upload the new version of themes and addons.
6) Restore everything backed up earlier.

**Comment by anaqreon** [comment]
Updating should be easy once the YunoHost package is updated to 2.0. You will not have to do all those steps. Unfortunately, I'm not really in a position to test this very well now, so I'm hoping @anmol26s can do this.

**Comment by anaqreon** [comment]
I've updated the source to support Hubzilla 2.0 (https://github.com/YunoHost-Apps/hubzilla-yunohost/tree/2.0.7). In the process of updating the installation scripts to the latest YunoHost, I may have broken support for old YunoHost versions. You will definitely want to make backups or take a snapshot of your virtual machine before installing this package, and until it has been tested more, you will need to consider this a "beta" version. I don't have the resources to extensively test this YunoHost package, especially since I run my hub manually (not via YunoHost). 

This is what I did to test the installation: I created a brand new virtual machine (a "droplet" on DigitalOcean) based on Debian 8 Jessie x64 and then performed the following steps:

1. sudo apt-get install git
2. git clone https://github.com/YunoHost/install_script /tmp/install_script
3. sudo passwd root
4. cd /tmp/install_script && sudo ./install_yunohost
5. echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
6. apt-get update
7. apt-get install certbot -t jessie-backports
8. Add YOUR_DOMAIN domain in YunoHost admin panel
9. service nginx stop
10. certbot certonly (install SSL certificate for YOUR_DOMAIN)
11. cp /etc/letsencrypt/live/YOUR_DOMAIN/fullchain.pem /etc/yunohost/certs/YOUR_DOMAIN/crt.pem
12. cp /etc/letsencrypt/live/YOUR_DOMAIN/privkey.pem /etc/yunohost/certs/YOUR_DOMAIN/key.pem 
13. service nginx start
14. Add new user in YunoHost admin panel
15. Install YunoHost Hubzilla package using GitHub URL

**Comment by isAAAc** [comment]
thx a lot;
done; (isaaac@soc.krashboyz.org)
looks fine for now, i'll give you a feedback tonight or tomorow

**Comment by anmol26s** [comment]
Thanks for the rescue @anaqreon 

I was using **git pull** for updating the Hubzilla till now. I updated from the Yunohost package, but now I don't receive the post updates and unable to connect to other hubs with remote authentication, I get "permission denied error ". @isAAAc can you please confirm the issue ? Can I have a account on your hub for testing ?

**Comment by isAAAc** [comment]
@anmol26s : 

- yes i confirm the issue not contact with external node ;/
- contact me on jabber/movim : isaaac@krashboyz.org  (or irc freenode (nickname : isAAAc)) for your account on my hub , but you should register yourself on the hub : https://soc.krashboyz.org

**Comment by anmol26s** [comment]
I have opened an issue [https://github.com/redmatrix/hubzilla/issues/668]( https://github.com/redmatrix/hubzilla/issues/668). By manually updating the database through Myphpadmin has fixed the remote login issue. But the other issue of no updates on the wall from the connected hubs is still not resolved. I don't know why the database updates are not being implemented automatically. As said in the link by @zotlabs that there may be other pending updates left which require manual updates too. I don't know how to test which updates are not yet implemented. Maybe @anaqreon can help ?

**Comment by isAAAc** [comment]
perhaps you can join this discussion too : https://lastauth.com/channel/kris/&f=&mid=712b70d680b2a897b5c2a2e43c5fb7ac5f1ae966411628cd993b6fc41e1e3afb@lastauth.com

**Comment by anaqreon** [comment]
When I removed the "well-known" line in the nginx configuration, the channel discovery and inter-hub communication began working. I am going to update the YunoHost package with this and a new setting for max upload size soon. I need to construct the "check_process" file before submitting a new commit, though, for the automated testing to say it passes.

**Comment by anmol26s** [comment]
I had missing updates for database. **/admin/dbsync/** shows no failed updates.The updates
update_r1181(),update_r1184(),update_r1179 were not implemented. I have to updated them manually. How can I know which updates have not been implemented yet and how can I run complex php update manually ?

**Comment by anaqreon** [comment]
I'm thinking we might need to make a clean break here and say that this 2.0 package is only intended for new installations on the latest YunoHost version. Who knows how many subtle bugs and conflicts there will be that we don't have the resources to address. It may be the case that Hubzilla is too complex for a YunoHost package without lots of experienced people maintaining it like the Nextcloud package for example.

**Comment by anaqreon** [comment]
I did a fresh installation of https://github.com/YunoHost-Apps/hubzilla-yunohost/commits/2.0.7b and I was able to add connections and they could post on my test channel's wall. I would like to close this issue and then you can open new issues for specific problems.

**Comment by isAAAc** [comment]
hi, i confirm the way i found yesterday : 
1 install hubzilla via yunohost
  yunohost app install hubzilla
2 create the first user && give him admin rights via phpmyadmin adding 4096 to the account_roles for the user  
3 backup the install to folder /var/www/hubzilla-bk-0213
4 delete the /var/www/hubzilla 
  cd rm -R hubzilla
5 import last sources from gitub && goto fresh hubzilla folder
  git clone https://github.com/redmatrix/hubzilla.git hubzilla
  cd hubzilla
6 remove source config files from && replace them by the backed up ones
  rm .htaccess 
  cp -rp ../hubzilla-bk-0213/.htconfig.php .
  cp -rp ../hubzilla-bk-0213/addons .
  cp -rp ../hubzilla-bk-0213/.htaccess .
  cp -rp ../hubzilla-bk-0213/store .
  cp -rp ../hubzilla-bk-0213/images/ .
7 change owner of the hubzilla folder to www-data 
 chown -R www-data:www-data /var/www/hubzilla

and now everything is ok and updated

**Comment by anaqreon** [comment]
This is a nice reference for others if they have similar problems, but I would prefer that we add a warning to the Readme that this is not an update release and that instead it is intended only for new installations on YunoHost 2.5. Hubzilla requires a fairly high level of competence for hub administrators, so those with existing hubs should be able to follow your solution to upgrade.

**Comment by isAAAc** [comment]
link to the relative post on ynh forum : [https://forum.yunohost.org/t/hubzilla-installation-debug/2490](url)
